### ISSUE TITLE
Flatpak

### ISSUE THREAD

**Issue by JakobDev** [mchlnix/SMB3-Foundry#155]
I created a [Flatpak](https://flatpak.org/) for SMB3-Foundry. This allows publishing on [Flathub](https://flathub.org) and installing on any Linux Distro out there (this does not work with the Binary). You need these files:

io.github.mchlnix.SMB3-Foundry.yaml
```yaml
id: io.github.mchlnix.SMB3-Foundry
runtime: org.kde.Platform
runtime-version: '6.5'
sdk: org.kde.Sdk
command: foundry
sdk-extensions:
  - org.freedesktop.Sdk.Extension.llvm16
build-options:
    append-path: /usr/lib/sdk/llvm16/bin
    prepend-ld-library-path: /usr/lib/sdk/llvm16/lib
finish-args:
  - --socket=fallback-x11
  - --socket=wayland
  - --share=ipc
  - --device=dri

modules:
  - name: qt-include
    # https://bugreports.qt.io/projects/PYSIDE/issues/PYSIDE-787
    buildsystem: simple
    build-commands:
      - mkdir -p /app/include/qt
      - cp -R /usr/include/Qt* /app/include/qt
    cleanup:
      - /include

  - name: PySide6
    buildsystem: cmake-ninja
    builddir: true
    config-opts:
      - -DCMAKE_BUILD_TYPE=Release
      - -DBUILD_TESTS=OFF
    sources:
      - type: archive
        url: https://download.qt.io/official_releases/QtForPython/pyside6/PySide6-6.5.1.1-src/pyside-setup-everywhere-src-6.5.1.1.tar.xz
        sha256: 9741a06f0b7d4b2168818448134bc7e96ddb5efb846a3915b4177ba4159b5b78
      - type: shell
        commands:
          # use qt-include
          - sed -i 's|\(--include-paths=\)|\1/app/include/qt:|' sources/pyside6/cmake/Macros/PySideModules.cmake
          # fix python module search path
          - sed -i '/--sys-path\b/ a "${pysidebindings_BINARY_DIR}/.."' sources/pyside6/cmake/Macros/PySideModules.cmake
    cleanup:
      - /plugins
      - /include
      - /bin

  - python3-modules.yaml

  - name: SMB3-Foundry
    buildsystem: simple
    build-commands:
      - mkdir -p $FLATPAK_DEST/SMB3-Foundry
      - cp -r * $FLATPAK_DEST/SMB3-Foundry
      - install -Dm755 foundry.sh $FLATPAK_DEST/bin/foundry
    sources:
      - type: archive
        archive-type: tar-gzip
        url: https://api.github.com/repos/mchlnix/SMB3-Foundry/tarball/1.2
        sha256: 96f01cde6059415d7dfe71ee00801df067b51660dfc19ae051289cd21ed76a45
        x-checker-data:
            type: json
            url: https://api.github.com/repos/mchlnix/SMB3-Foundry/releases/latest
            version-query: .tag_name
            url-query: .tarball_url
            is-main-source: true
      - type: script
        dest-filename: foundry.sh
        commands:
          - cd /app/SMB3-Foundry
          - exec python ./smb3-foundry.py
```

python3-modules.yaml
```yaml
# Generated with flatpak-pip-generator --yaml --checker-data py65 QDarkStyle
build-commands: []
buildsystem: simple
modules:
  - name: python3-py65
    buildsystem: simple
    build-commands:
      - pip3 install --verbose --exists-action=i --no-index --find-links="file://${PWD}"
        --prefix=${FLATPAK_DEST} "py65" --no-build-isolation
    sources:
      - type: file
        url: https://files.pythonhosted.org/packages/de/d0/8c07b2abfe19b4dad6640ac273e2b90072185425c1f3cdba7a82253597fa/py65-1.1.0-py2.py3-none-any.whl
        sha256: 43bae388727f130f7ce6fbadffc7d501fff05985b96813d2bcd3e6f00ea0d738
        x-checker-data:
          name: py65
          packagetype: bdist_wheel
          type: pypi
  - name: python3-QDarkStyle
    buildsystem: simple
    build-commands:
      - pip3 install --verbose --exists-action=i --no-index --find-links="file://${PWD}"
        --prefix=${FLATPAK_DEST} "QDarkStyle" --no-build-isolation
    sources:
      - type: file
        url: https://files.pythonhosted.org/packages/48/59/01f454d0eacb6670c77add68611b7a572455ae69ba902d270ed761869f87/QDarkStyle-3.1-py2.py3-none-any.whl
        sha256: 679a38fcd040de9fac8b8cae483310302fdb12c8d912845249c41dc54974a9b2
        x-checker-data:
          name: QDarkStyle
          packagetype: bdist_wheel
          type: pypi
      - type: file
        url: https://files.pythonhosted.org/packages/51/9f/495736f9bbebc56b9f2ba3d95df1045fd367378254f799e86463b0037ab0/QtPy-2.3.1-py3-none-any.whl
        sha256: 5193d20e0b16e4d9d3bc2c642d04d9f4e2c892590bd1b9c92bfe38a95d5a2e12
        x-checker-data:
          name: QtPy
          packagetype: bdist_wheel
          type: pypi
      - type: file
        url: https://files.pythonhosted.org/packages/ab/c3/57f0601a2d4fe15de7a553c00adbc901425661bf048f2a22dfc500caf121/packaging-23.1-py3-none-any.whl
        sha256: 994793af429502c4ea2ebf6bf664629d07c1a9fe974af92966e4b8d2df7edc61
        x-checker-data:
          name: packaging
          packagetype: bdist_wheel
          type: pypi
name: python3-modules
```

[Check out the Documentation how to build this](https://docs.flatpak.org/en/latest/first-build.html). Some things needs to be done e.g. launching the NES Emulator is not working, but it is general working. Tell me, if you are interested,
